### ISSUE TITLE
gPodder sync / AntennaPod sync

### ISSUE THREAD

**Issue by alexanderadam** [lucasasselli/garmin-podcasts#1]
Hi Luca,

first of all: thank you so much for creating an open source app for Garmin devices. :pray: 

Just little questions:
Is it somehow possible to sync the state with [gpodder](https://gpodder.net/) and/or [AntennaPod](https://github.com/AntennaPod/AntennaPod/)?
Or is it planned to implement this? If not: do you know any alternative that could do this?

**PS:** I think you should consider [adding a license file](https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/). Should this be [published under a FOSS license](https://choosealicense.com/)?

**Comment by lucasasselli** [comment]
Thank you for the suggestion! I added a GNU GPLv3 License.

I don't have any plan to integrate any external tool/service, but I'm receiving complaints about how clunky it is to add podcasts using the watch alone. ll review gpodder and AntennaPod.

**Comment by alexanderadam** [comment]
> Thank you for the suggestion! I added a GNU GPLv3 License.

That's great! :+1: 

> ll review gpodder and AntennaPod.

Even better! AntennaPod is just another app, so I _guess_ that it would be easier to add some gPodder auth fields to the garmin-podcasts settings and sync it this way. gPodder also allows the manage different devices.

But on the other hand I have no idea how these garmin things work. :wink: So maybe there's an easy way to simply send episodes via a tiny modification in AntennaPod.

**Comment by lucasasselli** [comment]
I checked gPodder: it looks like a great service that could improve a lot the app!

I want to add this feature but I want to do it as simple as possible. I'm reluctant to develop a complex client: Monkey C and Garmin SDK are terrible and have all sort of limitations.

This is how I see a possible implementation that works in the current framework:
- By default the user can search/add podcasts from the watch (as it is now)
- A gPodder mode can be enabled in the  settings (providing username and password)
- In gPodder mode the user can't add podcasts from the watch and gPodders subscriptions are used instead

The issues that I see with this approach are:
- gPodder subscriptions could be hundreds and the current flow of downloading the last N episodes for each podcast is not practical
- gPodder doesn't handle feed parsing, so Podcast Index is still needed
- Having a watch only and a gPodder only option could be confusing

I have to sleep on it.

**Comment by alexanderadam** [comment]
> I checked gPodder: it looks like a great service that could improve a lot the app!

Absolutely. The only issue I have, is that gpodder.net and its tools occasionally have various performance issues (see also issues like [59](https://bugs.gpodder.org/show_bug.cgi?id=59), [46](https://github.com/gpodder/mygpo/issues/46), [1172](https://bugs.gpodder.org/show_bug.cgi?id=1172), [414](https://github.com/gpodder/mygpo/issues/414), [486](https://github.com/gpodder/gpodder/issues/486), [205](https://github.com/gpodder/gpodder/issues/205), [612](https://github.com/gpodder/gpodder/issues/612), [842](https://github.com/gpodder/gpodder/issues/842)).

But it's a free service with a FOSS software after all. I'm just saying this because you might have to expect and handle sync timeouts. Probably no show stopper but AntennaPod ([2343](https://github.com/AntennaPod/AntennaPod/issues/2343#issuecomment-304643822), [2259](https://github.com/AntennaPod/AntennaPod/issues/2259#issuecomment-604716844)) and others also ran into it, so please don't be surprised if you're ecountering such issues. :wink: 

gPodder has the possibility to manage feeds for every device. It would be great if it would be possible to mark episodes in gPodder itself.

**Comment by lucasasselli** [comment]
I uploaded a new version on Garmin store! It implements gpodder sync. Tell me what you think!

**Comment by alexanderadam** [comment]
Oh wow, this is great!
Can you describe the suggested workflow?
I added my credentials to Garmin IQ Podcasts and when I press sync I'm getting `Check phone` on my watch and a notification on my phone. When I open that notification, it opens the browser with the gpodder website.

What should I do now?

I can see the watch under [`devices`](https://gpodder.net/devices/) listed as `Not Synchronized`.

**Comment by lucasasselli** [comment]
Well, that's weird. Selecting "Sync" should trigger the synchronization,
while selecting "Podcast" should open the notification. Can you confirm
that this is the case? What device are you using?

**Comment by alexanderadam** [comment]
Sorry, you're right — my fault. I probably got a wrong menu entry.
