### ISSUE TITLE
Forerunner 645 Music Support

### ISSUE THREAD

**Issue by dbuvid** [lucasasselli/garmin-podcasts#13]
Curious if it would be possible to add support for the 645 Music. I see that the 245 Music is supported and has the same API level as the 645 Music (3.2.0). I've been thinking of taking a stab at it myself but not being familiar with Connect IQ I figured I would check to see if there was some limitation preventing the 645 Music from being supported.

Looks like a really promising app and I would love to be able to check it out on my watch!

**Comment by lucasasselli** [comment]
Hi, just added support for the Forerunner 645 music! Check out version 3.1.3!
