### ISSUE TITLE
fenix 7

### ISSUE THREAD

**Issue by pelicangris** [lucasasselli/garmin-podcasts#19]
Hi,
Any chance the new fenix 7 could be added to the list of supported device?
I have tried to fork and build myself but this seems to be above my limited technical skills.
Thanks!

**Comment by drivenbyentropy** [comment]
I second this. Absolutely loved this app on my Fenix 6s and hope to see it available on the Fenix 7s soon. Thank you for the amazing work with this project!

**Comment by spitedoggie** [comment]
Would love 7x support as well !  Thanks!

**Comment by lucasasselli** [comment]
Version 3.1.10 on the store adds support for Fenix 7.

**Comment by pelicangris** [comment]
thank you so much!
