### ISSUE TITLE
Add nextcloud support

### ISSUE THREAD

**Issue by pelicangris** [lucasasselli/garmin-podcasts#20]
Hi,
gpodder.net unfortunately doesn't allow new registrations. I have tried to self host but almost lost my sanity.
There is however a nextcloud app that replicates the gpodder api: https://github.com/thrillfall/nextcloud-gpodder
Is this something that can be added to this garmin app?

**Comment by lucasasselli** [comment]
I haven't checked the docs. But I think that as long as the API is the same you should be able to set your Nextcloud host in the app settings and roll with it.

**Comment by pelicangris** [comment]
Thank you. As far as I understand the API are the same but the authentication differs. The développer of gpoddersync has pushed an update to the antennapod android client to introduce an alternative sync option.

**Comment by lucasasselli** [comment]
@pelicangris, Nexcloud support should be available in v3.3.3. Please create and "App password" in Nextcloud and use it to login.

**Comment by pelicangris** [comment]
That's great! Thank you so much!

**Comment by lucasasselli** [comment]
Let me know if you have any issues.

**Comment by pelicangris** [comment]
Hi, tried to use it but when I try to manage subscriptions from the watch it spins 'Loading' for a minute or two and then goes back to the watch face.
