### ISSUE TITLE
Nextcloud sync not working

### ISSUE THREAD

**Issue by pelicangris** [lucasasselli/garmin-podcasts#22]
Hi,
I have tried to set up the nextcloud sync but no luck.
When I try to download the episodes from the watch, I get a spinning 'Loading' until it gives up and goes back to the watch face. Any hint at what to try next?
Thanks!

**Comment by pelicangris** [comment]
Restarted the watch... Now works!

**Comment by pelicangris** [comment]
Restarted the watch and it now works!

**Comment by lucasasselli** [comment]
Great stuff!
