### ISSUE TITLE
Stuck in "Syncing Podcasts Provider 2 of 2"

### ISSUE THREAD

**Issue by alexanderadam** [lucasasselli/garmin-podcasts#3]
I'm not quite sure whether this is related to your Garmin Podcasts app but maybe you have an idea.

Every now and then, the watch gets stuck while syncing. It stays in the following screen:

![Syncing Podcasts Provider 2 of 2](https://user-images.githubusercontent.com/372620/100599575-7f148580-3300-11eb-8362-4bf23dd40596.png)

Again, thank you so much for your work! :pray:

**Comment by lucasasselli** [comment]
Hi Alexander,

My watch is out for repairs so I can't reproduce the issue. Are you using gpodder?

**Comment by alexanderadam** [comment]
> My watch is out for repairs so I can't reproduce the issue.

No pressure on that. Take all the tiime you need. I'm already happy that you did such a great job with this app! :pray: 

> Are you using gpodder?

Yes I am.

**Comment by dallanmc** [comment]
@lucasasselli is the sync sometimes triggered automatically? I think it seems to happen when I have the watch charging?

**Comment by alexanderadam** [comment]
> I think it seems to happen when I have the watch charging?

I can confirm that it always appears on charging for me as well.

**Comment by lucasasselli** [comment]
I tried to reproduce this issue on my side with little success. Do you have more than 1 provider? What is the second?

**Comment by alexanderadam** [comment]
> Do you have more than 1 provider? What is the second?

This might be a stupid question but what is a provider in this regards and how can I check for providers? :thinking:

**Comment by mmirate** [comment]
Another music-playing app, one that shows up in the same part of the Connect IQ store as this one. e.g. Deezer, Spotify, Amazon Music or that Subsonic client whose name presently escapes me.

**Comment by alexanderadam** [comment]
> Another music-playing app, one that shows up in the same part of the Connect IQ store as this one. e.g. Deezer, Spotify, Amazon Music or that Subsonic client whose name presently escapes me.

Ah okay. I only have two Music apps installed: Garmin Podcasts and Spotify.

**Comment by alexanderadam** [comment]
> I can confirm that it always appears on charging for me as well.

Just to clarify: this happens _only_ when charging. Not on any other occasion.

**Comment by lucasasselli** [comment]
Hi Alexander,

This looks to be an issue on Garmin side:
https://forums.garmin.com/developer/connect-iq/i/bug-reports/bug-media-communications-syncdelegate-blocks-charging

That being said, one of the users mentioned a workaround. Let me see if I can do something similar...

**Comment by lucasasselli** [comment]
I implemented the workaround in version 3.0.2. I couldn't trigger the error again on my side.

**Comment by alexanderadam** [comment]
I can confirm that this bug is fixed now. Thank you Luca! :+1:
