### ISSUE TITLE
Feature request: gpodder nextcloud

### ISSUE THREAD

**Issue by fyksen** [lucasasselli/garmin-podcasts#32]
The API is a small change from vanilla gpodder. 
Github: https://github.com/thrillfall/nextcloud-gpodder

"nextcloud-gpodder
Nextcloud app that replicates basic gpodder.net api to sync podcast consumer apps (podcatchers) like AntennaPod."

**Comment by lucasasselli** [comment]
This was implemented in #20.

**Comment by fyksen** [comment]
Uhh, I am so sorry. Thanks!
