### ISSUE TITLE
No episodes in playback queue after sync

### ISSUE THREAD

**Issue by nerdiges** [lucasasselli/garmin-podcasts#4]
Hi,

I just installed the the App via connect IQ, added a podcast and started a sync. The sync seems to be successful - or at least I did not receive an error message. But after the sync there are no Episodes in the playback queue.

I am not using gpodder yet.

Am I missing something?

Thank you very much in advance,
Stephan

**Comment by mmirate** [comment]
If you select the "Playback queue" / "0 episodes" menu item, you'll get a menu that allows you to manually select some episodes to add to the playback queue. The queue just isn't populated automatically.

**Comment by nerdiges** [comment]
Sorry for the late response. If I select the menu entry "Playback queue" / "0 episodes" I just recieve teh message "No episodes downloaded!" although the sync seems to be successful. Do I have to trigger the download somewhere else? 

I'm using Garmin Fenix 6 Pro with latest firmware version and latest version of podcastas IQ app.

![01_Syncing](https://user-images.githubusercontent.com/4491736/101920895-a99df280-3bcc-11eb-810a-f57252fa4457.jpg)
![02_SyncSuccess](https://user-images.githubusercontent.com/4491736/101920900-ab67b600-3bcc-11eb-80ce-f030fb794f1c.jpg)
![03_PlaybackQueue](https://user-images.githubusercontent.com/4491736/101920904-ac98e300-3bcc-11eb-9411-ecff166aeb40.jpg)
![04_NoEpisodes](https://user-images.githubusercontent.com/4491736/101920910-ad317980-3bcc-11eb-8689-43e21c20f787.jpg)
![05_Settings](https://user-images.githubusercontent.com/4491736/101920915-ae62a680-3bcc-11eb-9752-75b3edaac5e6.jpg)
![06_Settings](https://user-images.githubusercontent.com/4491736/101920924-b0c50080-3bcc-11eb-9388-91659ec3a940.jpg)

**Comment by lucasasselli** [comment]
It's very likely an issue with the podcast itself. 

If the file can't be downloaded the app tries to get the rest, if no file can be downloaded you will end up with this. 

Unfortunately, the only way to issue an error to the user stops the sync process, so a possible solution should be do it at the end of the sync if there are issues.

**Comment by lucasasselli** [comment]
I added an error message in version 2.0.2 if some download fails.
