### ISSUE TITLE
Triple play buttons

### ISSUE THREAD

**Issue by st-a** [lucasasselli/garmin-podcasts#6]
I don't know if this is intended behaviour, but I get three play buttons once the playback queue is populated. On the right side is the content of the `...` menu. The device is a *vívoactive 4* running firmware version `5.10.0.0`.

![play-buttons](https://user-images.githubusercontent.com/4363856/102691548-98c53080-420d-11eb-98b7-ec61a073a4d4.jpg)

Is there any reason for the white background behind the podcast app logo displayed on the right side? I would be happy to supply a pull request with transparent resource files if modifying the `png` files is the only thing required.

**Comment by lucasasselli** [comment]
This is not the intended behaviour. Unfortunately on the device simulator everything looks fine.

**Comment by lucasasselli** [comment]
I delivered a fix for this on 2.0.2. Please tell me if you still see this.

**Comment by st-a** [comment]
Thanks a lot for the update! Unfortunately I am not able to play back anything anymore.

1. Open the app and add episodes to the queue. Touch `Done`.
2. On the following screen all buttons except the three dots are greyed out. Touching play does nothing. There is no episode title displayed. Touching the upper screen toggles the display of `0:00`.
3. Another bug: the app icon is invisible now. Touching the invisible 6th position below the volume icon opens the Podcasts settings.
4. There is also no icon in the `Music Providers` selection menu.

![play-buttons2](https://user-images.githubusercontent.com/4363856/104181053-6e325600-540e-11eb-8d15-f633378b73b0.jpg)

**Comment by lucasasselli** [comment]
Can you try to uninstall and reinstall? It should fix the playback issue.

I'll investigate the invisible icon.

**Comment by st-a** [comment]
Reinstalling fixed the Problem! No more triple play buttons. But the icon is still invisible.

**Comment by lucasasselli** [comment]
The icon should be fixed in version 2.0.3. Please let me know if it's okay!

**Comment by st-a** [comment]
Looks great. Thanks!
