### ISSUE TITLE
Playback queue has incorrect number of episodes

### ISSUE THREAD

**Issue by dallanmc** [lucasasselli/garmin-podcasts#7]
Here's the scenario: 
1 subscribed podcast. 
Max episodes per podcast: 1

Sync and there is a new podcast. Select the episode in the playback queue. 
Menu now has "Playback queue. 1 Episodes"

All good so far. 

But now let's say you sync and there's a new episode. What happens now is that the new episode gets downloaded and added to the queue. The old episode drops off (because it's only 1 episode per podcast), BUT it hasn't been removed from the Constants.STORAGE_PLAYLIST playlist. 

Now when you select the new episode, it will add it to the Constants.STORAGE_PLAYLIST playlist, but the old one will also be stored in there. 

Now the total number of episodes is 2, but there is only one episode visible. The total number should be 1.

**Comment by lucasasselli** [comment]
Nice catch! 👍 I delivered a fix for this issue in version 2.0.2. You might have to sync to see the old episodes purged from the queue.
