### ISSUE TITLE
Add manifest entries for Fenix 5 Plus series watch products 

### ISSUE THREAD

**Issue by ratamaa** [lucasasselli/garmin-podcasts#8]
I only cloned the repo and added Fenix 5 Plus product entry to manifest.xml: 
```
            <iq:product id="fenix5plus"/>
```
compiled locally with newest SDK and transferred to my Fenix 5 Plus Sapphire watch (with a new API key).
The application seems to work fine for me. Episodes can be searched, subscribed, synced and played. It displays artwork and as far as I understand, works as expected.

It would be nice if the official application in the Connect IQ store would support Fenix 5 Plus directly.
The Fenix 5 Plus lineup was the first to receive Spotify support and currently supports the minimum API version 3.2.0.

There are also 5S Plus and 5X Plus watches that I can't test, but entries for them would be:
```
            <iq:product id="fenix5splus"/>
            <iq:product id="fenix5xplus"/>
```

**Comment by lucasasselli** [comment]
Hi, 
 I'm having trouble to build the app for the F5Plus.

`ERROR: Device 'fenix5plus' does not support SDK version '3.2.0'.`

How did you build it?

**Comment by lucasasselli** [comment]
Added support for Fenix 5 family in version 2.1.0.
